service: usahs-hello

package:
  exclude:
    - node_modules/**
    - package*.json
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  deploymentBucket:
    name: usahs-deploys
  versionFunctions: false

  environment:
    NODE_PATH: './:/opt/node_modules'
  
  layers:
    #  - !ImportValue usahs-nodelayers-nodeTenArn-${self:provider.stage}
    - ${cf:usahs-nodelayers-${self:provider.stage}.nodeTenArn}

functions:
  hello:
    name: ${self:service}-${self:provider.stage}
    handler: handler.hello
