name: dev-actions
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  check-bats-version:
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      STAGE: 'dev'
      REGION: 'us-east-1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g serverless
      - run: ./deploy.sh $STAGE $REGION
